### ISSUE TITLE
Custom check results get wiped from target if "Create new check" is used

### ISSUE THREAD

**Issue by putsi** [swissfondue/gtta#16]
Hey, I noticed following bug:
1. User tests a target which uses **Checklist Template** as a check source.
2. User then uses the _Custom Check_ functionality to create a custom vulnerability and selects the **"Create new check"**-checkbox.
3. The vulnerability is now saved to the target and a new check is created.
4. The new check however is not added to the **Checklist Template** used by the target.
5. After a while, some cleanup-functionality happens (resque-worker?). The functionality sees that the target contains a check which is not enabled on the **Checklist Template** and then removes it from the target.
6. This results in vulnerability data being deleted and it won't be recovered after the user manually enables the check on the template.

TL;DR:
When the **"Create new check"** is used with custom checks, the functionality should also enable the check in checklist template if such used by the target.

**Comment by anton-belousov** [comment]
Fixed in 2.4
