### ISSUE TITLE
Add licence for the project

### ISSUE THREAD

**Issue by putsi** [swissfondue/gtta#2]
> Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

This repo is missing a licence declaration. 
Can you add a licence-file that indicates what users are allowed and not allowed to do with the project?
Here's a link to a site that compares various OSS-licences: https://choosealicense.com/

**Comment by anton-belousov** [comment]
LICENSE file is added to the repo. Thank you!
