### ISSUE TITLE
object detection API

### ISSUE THREAD

**Issue by ShaniOl** [swissfondue/gtta#27]
Hi,
I've been using Training Custom Object Detector - Tensorflow Object Detection API to train on my own data. I couldn't find a way to see the precision. 
Any idea how it could be done?

https://pythonprogramming.net/creating-tfrecord-files-tensorflow-object-detection-api-tutorial/

**Comment by anton-belousov** [comment]
@ShaniOl sorry, I think you were going to post this issue to some other repository.
