### ISSUE TITLE
Add protection against accidental overwriting of other user's target_check values

### ISSUE THREAD

**Issue by putsi** [swissfondue/gtta#5]
When two users are collaborating on a pentest and are making changes to the same target (e.g. https://gtta.local/project/1/target/4/category/13), the changes are not automatically synced between the users (i.e. user2 must reload the page to see modifications of user1). This can lead to a situation where one user accidentally overwrites changes made by another user.

Best way to fix this would probably be implementation of automatic Ajax-based value updating.
However I'm opting for last-modification-timestamp based safety check as that is fairly trivial to implement.

Any comments on this?

**Comment by swissfondue** [comment]
I have not best experience with ajax updating as it eats up resources (server/traffic..) and can also might create small lags in the browser. We use that in Lucy and I regret now having implemented that…  Timestamp would be sufficient I guess. We also very rarely have 2 simultaneous users working on same project 

 

Von: Jarmo Puttonen [mailto:notifications@github.com] 
Gesendet: Freitag, 28. April 2017 16:39
An: swissfondue/gtta <gtta@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [swissfondue/gtta] Add protection against accidental overwriting of other user's target_check values (#5)

 

When two users are collaborating on a pentest and are making changes to the same target (e.g. https://gtta.local/project/1/target/4/category/13), the changes are not automatically updated between the users (i.e. user2 must reload the page to see modifications of user1). This can lead to a situation where one user accidentally overwrites changes made by another user.

Best way to fix this would probably be implementation of automatic Ajax-based value updating.
However I'm opting for implementation of a last-modification-timestamp based safety check as that is fairly trivial to implement.

Any comments on this?

**Comment by putsi** [comment]
Allright, I'll start working on the timestamp-based protection and will submit a pull request when its done.

**Comment by anton-belousov** [comment]
Merged. Thanks, @putsi
